#!/bin/bash

pack_up() {
    awk -f $DIR/$template_dir/$template/meta-head.awk
    # wrap up with style of font-size
    grep -b "div id=\"content\"" | sed 's/.*<div id="content">//' |
        awk '{print "<p style=\"font-size: 20px;\">"$0"</p>"}'
}