#!/bin/bash
#
# Hummingbird - A bash framework for novel crawlers
# Copyright (C) 2020    Jason
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

DIR=${0%/*}

source $DIR/env

# check existence of a function
check_func() {
    local prompt
    local ret=0

    missing_func=
    for func in $*; do
        prompt=$(type $func >/dev/null)
        [ $? -ne 0 ] && {
            echo $prompt
            missing_func+="$func "
            ret=1
        }
    done

    return $ret
}

# Load Log library
log_style=colorful
log_file=$DIR/hummingbird-$(date +%Y-%m-%d).log
source $DIR/log-styles/$log_style/utils

# check write_log
check_func write_log
[ $? -ne 0 ] && exit 1

# using mutt to send mail
mail_lib=mutt
source $DIR/mail/$mail_lib/utils
[ $debug -gt 0 ] && {
    unset send_mail
    send_mail() {
        tee
    }
}

# check mail functions
check_func write_log
[ $? -ne 0 ] && {
    write_log "error" \
        "Missing function $missing_func in mail library $mail_lib"
    exit 1
}

# autoload config
ls $DIR/$conf_dir | while read conf; do
    # load settings
    source $DIR/$conf_dir/$conf
    source $DIR/$driver_dir/$driver/utils
    source $DIR/$template_dir/$template/utils

    # check functions
    check_func \
        check_list fetch_page pack_up
    [ $? -ne 0 ] && {
        # missing_func was generated by check_func,
        # end with a space char
        write_log "error" \
            "Missing function(s) ${missing_func}in driver $driver"
        exit 1
    }

    # scheduled tasks
    ret=0
    check_list
    ret=$?
    [ $debug -gt 1 ] || [ $ret -eq 0 ] &&
        fetch_page | pack_up | send_mail
done
