#!/bin/bash

# URL settings
site=https://www.kuxiaoshuo.com
index=$site/$id
page=$site/$id/$page_id/

# cache file settings
index_cache=/tmp/kuxiaoshuo-cache-$id
check_cache=/tmp/kuxiaoshuo-check-cache-$id

# TODO check for charset
fetch() {
    curl -s $1 | iconv -f GBK -t UTF8
}

check_diff() {
    [ "$1" == "$2" ]
    return $?
}

check_list() {
    local ret=0

    touch $check_cache
    fetch $index >$index_cache
    local res=$(cat $index_cache | grep "<dd>" | tail -n1)

    check_diff "$(echo $res | sed 's/.*href=\"//;s/\">.*//')" \
        "$(cat $check_cache | sed 's/.*href=\"//;s/\">.*//')"
    if [ $? -eq 0 ]; then
        ret=1
    else
        printf "%s" "$res" >$check_cache
    fi

    return $ret
}

fetch_page() {
    name=$1
    url=$(sed 's/.*href=\"//;s/\">.*//' $check_cache)
    chapter=$(sed 's/<\/a.*//;s/.*>//' $check_cache)

    while :; do
        curl -s $url | iconv -f GBK >/tmp/kuxiaoshuo-$id
        [ $? -eq 0 ] && break
        sleep 3
    done

    cat <<END
$name
$chapter
---
END
    cat /tmp/kuxiaoshuo-$id
}
