#!/bin/bash
#
# Hummingbird - A bash framework for novel crawlers
# Copyright (C) 2020    Jason
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# URL settings
site=https://www.kuxiaoshuo.com
index=$site/$id
page=$site/$id/$page_id/

# Cache file settings
index_cache=/tmp/kuxiaoshuo-cache-$id
check_cache=/tmp/kuxiaoshuo-check-cache-$id

fetch() {
    curl -s $1 | iconv -f GBK -t UTF8
}

check_diff() {
    [ "$1" == "$2" ]
    return $?
}

check_list() {
    local ret=0
    local tmpfile=/tmp/$driver-tmp-$id

    touch $check_cache
    write_log "info" "Fetching index page of $name [$id]"
    fetch $index >"$tmpfile"
    local res=$(cat $tmpfile | grep "<dd>" | tail -n1)
    [ "$res" == "" ] && {
        write_log "warning" "Got empty list of $name [$id]"
        return 1
    }
    mv $tmpfile $index_cache

    # only checks for URL
    check_diff "$(echo $res | sed 's/.*href=\"//;s/\">.*//')" \
        "$(cat $check_cache | sed 's/.*href=\"//;s/\">.*//')"
    if [ $? -eq 0 ]; then
        ret=1
    else
        printf "%s" "$res" >$check_cache
    fi

    return $ret
}

fetch_page() {
    url=$(sed 's/.*href=\"//;s/\">.*//' $check_cache)
    chapter=$(sed 's/<\/a.*//;s/.*>//' $check_cache)
    write_log "info" "Trying to get chapter [$chapter] of $name [$id]"

    while :; do
        write_log "info" "Fetching page $url"
        curl -s $url | iconv -f GBK >/tmp/kuxiaoshuo-$id
        [ $? -eq 0 ] && break
        write_log "warning" "iconv: Format convert failed"
        sleep 3
    done

    cat <<END
$name
$chapter
---
END
    # wrap up with style of font-size
    cat /tmp/kuxiaoshuo-$id | grep -b "div id=\"content\"" |
        sed 's/.*<div id="content">//' |
        awk '{print "<p style=\"font-size: 20px;\">"$0"</p>"}'
}
